{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pagamento.fullname" . }}-network-policy
  namespace: {{ .Values.namespace.name | default "fastfood" }}
  labels:
    {{- include "pagamento.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pagamento.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- range .Values.networkPolicy.allowedNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .name }}
      ports:
        - protocol: TCP
          port: 8000
    {{- end }}
{{- end }}

