name: CI/CD Pipeline

on:
  push:
    branches:
      - cd/teste
  workflow_dispatch:

env:
  REGISTRY: acrfastfoodpostech.azurecr.io
  APP_IMAGE_NAME: fastfood/pagamento # Alterado para não sobrescrever Users
  AKS_RESOURCE_GROUP: rg-fastfood-postech
  AKS_CLUSTER_NAME: aks-fastfood-postech
  NAMESPACE: fastfood

jobs:
  build-and-push-acr:
    name: Build and Push to ACR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Obrigatório para OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_KAUAN }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_KAUAN }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_KAUAN }}

      - name: Log in to ACR
        run: az acr login --name acrfastfoodpostech

      - name: Extract version
        id: version
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.version.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest

  deploy-aks:
    name: Deploy to AKS
    needs: [build-and-push-acr]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_KAUAN }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_KAUAN }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_KAUAN }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Deploy with Helm
        run: |
          helm upgrade --install pagamento ./helm/pagamento \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --set image.repository=${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }} \
            --set image.tag=${{ github.sha }} \
            --wait